name: Node CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: ESlint Runner Action
      uses: tinovyatkin/action-eslint@v1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        check-name: eslint
